# http
quarkus.http.port=8082
quarkus.http.test-port=8085
quarkus.http.enable-compression=true
quarkus.http.enable-decompression=true

# http cache
quarkus.http.static-resources.max-age=P365d
## make sure the webapp is always up to date
quarkus.http.filter.index-html.header."Cache-Control"=no-cache
quarkus.http.filter.index-html.matches=/
## make sure the openapi documentation is always up to date
quarkus.http.filter.openapi.header."Cache-Control"=no-cache
quarkus.http.filter.openapi.matches=/openapi
## make sure /next always redirects to the next unread entry
quarkus.http.filter.next.header."Cache-Control"=no-cache
quarkus.http.filter.next.matches=/next

# security
quarkus.http.auth.basic=true
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.http-only-cookie=true
quarkus.http.auth.form.timeout=P30d
quarkus.http.auth.form.cookie-max-age=P30d
quarkus.http.auth.form.landing-page=
quarkus.http.auth.form.login-page=
quarkus.http.auth.form.error-page=

# websocket
quarkus.websocket.dispatch-to-worker=true

# database
quarkus.liquibase.change-log=migrations.xml
quarkus.liquibase.migrate-at-start=true

# openapi
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/api-documentation
quarkus.swagger-ui.always-include=true

# shutdown
quarkus.shutdown.timeout=5s

# native
quarkus.native.march=compatibility
quarkus.native.add-all-charsets=true
# compatibility fix for native builds
quarkus.native.additional-build-args=-H:PageSize=65536


# dev profile overrides
%dev.quarkus.http.port=8083
%dev.quarkus.datasource.jdbc.url=jdbc:h2:./data/dev-db;DEFRAG_ALWAYS=TRUE
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa
%dev.quarkus.http.auth.session.encryption-key=123456789012345678901234567890
%dev.quarkus.log.category."com.aynreader".level=DEBUG
# %dev.quarkus.hibernate-orm.log.sql=true
%dev.aynreader.users.create-demo-account=false


# test profile overrides
%test.quarkus.log.category."org.mockserver".level=WARN
%test.quarkus.log.category."liquibase".level=WARN
%test.aynreader.shutdown-timeout=100ms
%test.aynreader.users.create-demo-account=true
%test.aynreader.users.allow-registrations=true
%test.aynreader.password-recovery-enabled=true
%test.aynreader.http-client.cache.enabled=false
%test.aynreader.http-client.block-local-addresses=false
%test.aynreader.database.cleanup.entries-max-age=0
%test.aynreader.feed-refresh.force-refresh-cooldown-duration=1m
## GitHub actions runners are very slow, we need to increase this timeout to avoid intermittent test failures
%test.aynreader.feed-refresh.filtering-expression-evaluation-timeout=1s

# prod profile overrides
%prod.quarkus.datasource.jdbc.url=jdbc:h2:./data/db;DEFRAG_ALWAYS=TRUE
%prod.quarkus.datasource.username=sa
%prod.quarkus.datasource.password=sa
%prod.quarkus.log.category."com.rometools.modules".level=ERROR
